#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: compile file..."
    exit 1
fi

if [ "$1" == "-g" ]; then
    for name in "$@"
    do
        case "$name" in
            -g)
                ;;
            *.c)
                gcc -O2 -g -o "${name%.*}" "${name}"
                ;;
            *.cc)
                g++ -O2 -g -o "${name%.*}" "${name}"
                ;;
            *.cpp)
                g++ -O2 -g -o "${name%.*}" "${name}"
                ;;
            *)
                echo "$(basename "${name}") is not my type."
                ;;
        esac
    done
else
    for name in "$@"
    do
        case "$name" in
            *.c)
                gcc -O2 -o "${name%.*}" "${name}"
                ;;
            *.cc)
                g++ -O2 -o "${name%.*}" "${name}"
                ;;
            *.cpp)
                g++ -O2 -o "${name%.*}" "${name}"
                ;;
            *.java)
                javac -Xlint "${name}"
                ;;
            *.py)
                ;;
            *.rs)
                rustc -O --out-dir "$(dirname "${name}")" "${name}"
                ;;
            *)
                echo "$(basename "${name}") is not my type."
                ;;
        esac
    done
fi
