#!/bin/sh

for name in "$@"
do
    case "$name" in
        *.java)
            java.exe -classpath "`wslpath -w "$(dirname "$name")"`" "$(basename "${name%.*}")"
            ;;
        *.class)
            java.exe -classpath "`wslpath -w "$(dirname "$name")"`" "$(basename "${name%.*}")"
            ;;
        *.py)
            python3 "${name}"
            ;;
        *.c)
            "${name%.*}"
            ;;
        *.cc)
            "${name%.*}"
            ;;
        *.cpp)
            "${name%.*}"
            ;;
        *)
            "${name}"
            ;;
    esac
done
